version: '3'
services:
  loadbalancer:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - service1
      - service2
  service1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  service2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"