fhir:
  remote-structure-servers:
    structure01:
      url: "https://term01.itcr.uni-luebeck.de/fhir"
    structure02:
      url: "https://structure02.itcr.uni-luebeck.de/fhir"
      auth-user: "username"
      auth-password: "password"
      override-page-size: 42

  remote-terminology-servers:
    term01:
      url: "https://term01.itcr.uni-luebeck.de/fhir"
    term02:
      url: "https://term02.itcr.uni-luebeck.de/fhir"

  retrieval-page-size: 100