fhir:
  remote-structure-servers:
    hapi:
      url: "${STRUCTURE_SERVER_URL}"
      override-retrieve-only-active-profiles: false

  remote-terminology-servers:
    onto:
      url: "${TERMINOLOGY_SERVER_URL}"

  retrieval-page-size: 100

server:
  port: ${PORT}

logging:
  level:
    de.uksh: debug