fhir:
  remote-structure-servers:
    hapi:
      url: "http://localhost:8080/fhir"
      override-retrieve-only-active-profiles: false

  remote-terminology-servers:
    onto:
      url: "https://ontoserver.imi.uni-luebeck.de/fhir"

  retrieval-page-size: 100

server:
  port: 8081

logging:
  level:
    de.uksh: debug